web:
  image: nginx:latest
  ports:
    - 8080:80
  volumes:
    - ./app:/var/www/app
    - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
  links:
    - phpfpm

phpfpm:
  image: php:7-fpm
  volumes:
    - ./app:/var/www/app